/** auto-generated by laraveltypesgen */

export interface StoreOrderRequest {
  customer_email: string;
  shipping_address: {
    street: string;
    city: string;
    zip: string;
    country: string;
  };
  items: {
    product_id: number;
    quantity: number;
    price: number;
  }[];
  coupon_code?: string | null;
  notes?: string | null;
}

export interface StoreProductRequest {
  name: string;
  description?: string | null;
  price: number;
  stock: number;
  category_id: number;
  active: boolean;
  images?: any[] | null;
  meta?: any | null;
}

export interface StoreUserRequest {
  name: string;
  email: string;
  password: string;
  age?: number | null;
  bio?: string | null;
  avatar?: File | null;
}

export interface UpdateUserRequest {
  name?: string;
  email?: string;
  bio?: string | null;
  avatar?: File | null;
}

