/** auto-generated by laraveltypesgen */

export interface OrderResource {
  id: any;
  customer_email: any;
  status: any;
  total: any;
  payment_id: any;
  shipping_address: any;
  coupon_code: any;
  notes: any;
  created_at: any;
}

export interface ProductResource {
  id: number;
  name: string;
  description: string | null;
  price: number;
  stock: number;
  category_id: number;
  active: boolean;
  meta: string | null;
  created_at: string;
}

export interface UserResource {
  id: number;
  name: string;
  email: string;
  avatar_url: string;
  bio: string;
  created_at: string;
}

